trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: First Job
    steps:    
    - bash: echo build first job
  - job: Second Job
    steps:    
    - bash: echo build second job

- stage: Quality Check
- stage: DevDeploy
  jobs: 
  - job: DevDeploy Job
    steps:    
    - bash: echo Dev Deploy job
- stage: QADeploy
  jobs: 
  - job: QADeploy Job
    steps:    
    - bash: echo QA Deploy Job
- stage: ProdDeploy
  jobs: 
  - job: ProdDeploy Job
    steps:    
    - bash: echo prod deploy job
