trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:    
    - bash: echo buildfirstjob
  - job: SecondJob
    steps:    
    - bash: echo buildsecondjob

- stage: QualityCheck
  dependsOn: Build
  jobs: 
  - job: QualityCheckJOB
    steps:    
    - bash: echo qualitycheckjob
- stage: DevDeploy
  dependsOn: 
  - Build
  - QualityCheck
  jobs: 
  - job: DevDeployJob
    steps:    
    - bash: echo DevDeployjob
- stage: QADeploy
  dependsOn: 
  - Build
  - QualityCheck
  jobs: 
  - job: QADeployJob
    steps:    
    - bash: echo QADeployJob
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs: 
  - job: ProdDeployJob
    steps:    
    - bash: echo proddeployjob
