trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstBuildJob
    steps:
    - bash: echo build First Job
    displayName: 'First build Job'
  - job: SecondBuildJob
    steps:
    - bash: echo build First Job
    displayName: 'Second build Job'
  
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeploy First Job
    displayName: 'First DevDeploy build Job'
  
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeploy First Job
    displayName: 'First QADeploy build Job'
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: PRODDeployJob
    steps:
    - bash: echo PRODDeploy First Job
    displayName: 'First PRODDeploy build Job'