trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps:    
    - bash: echo buildfirstjob
    - bash: echo $(PipelineLevelvariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchname)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(Build.DefaultWorkingDirectory)
    - bash: ls -R $(Build.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
  - job: SecondJob
    steps:    
    - bash: echo buildsecondjob

- stage: QualityCheck
  dependsOn: Build
  jobs: 
  - job: QualityCheckJOB
    steps:    
    - bash: echo qualitycheckjob
- stage: DevDeploy
  variables:
    environment: dev
  dependsOn: 
  - Build
  - QualityCheck
  jobs: 
  - job: DevDeployJob
    steps:    
    - bash: echo $(environment)Deployjob
- stage: QADeploy
  variables:
    environment: QA
  dependsOn: 
  - Build
  - QualityCheck
  jobs: 
  - job: QADeployJob
    steps:    
    - bash: echo $(environment)DeployJob
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs: 
  - job: ProdDeployJob
    steps:    
    - bash: echo $(environment)deployjob
