trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstBuildJob
    steps:
    - bash: echo build First Job
    - bash: echo $(PipelineLevelvariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: maven --version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    displayName: 'First build Job'
  - job: SecondBuildJob
    steps:
    - bash: echo build First Job
    displayName: 'Second build Job'
  
- stage: DevDeploy
  variables:
    environment: Dev  
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)Deploy First Job
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    displayName: 'First DevDeploy build Job'
  
- stage: QADeploy
  variables:
    environment: QA
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment)Deploy First Job
    displayName: 'First QADeploy build Job'
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: PRODDeployJob
    steps:
    - bash: echo PRODDeploy First Job
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    displayName: 'First PRODDeploy build Job'