trigger:
- main

resources:
- repo: self

variables:
#  tag: '$(Build.BuildId)'
   tag: 37 

# Stage 1
# Build Docker Image
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        containerRegistry: 'in28min-docker-hub'
#        repository: 'sameeryalla/currency-exchange-devops'
#        command: 'buildAndPush'
#        Dockerfile: '**/Dockerfile'
#        tags: '$(tag)'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/*.yaml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
# Publish the K8S Files
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'manifests'
          publishLocation: 'Container'


# Stage 2
# Download the K8S File
- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: |
          **/*.yaml
          **/*.yml
        targetPath: '$(System.ArtifactsDirectory)'
# Deploy to K8S Cluster with Docker Image
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
        containers: 'sameeryalla/currency-exchange-devops:$(tag)'